version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=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
      - GEMINI_API_KEY=AIzaSyAj5LP79_6DuXh_JR2nHBTWvxKno7VQvDE
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped 